### ISSUE TITLE
Binary to Base 4

### ISSUE THREAD

**Issue by hlpostman** [emkk/text2dna#6]
We need to further encode the binary representations of ASCII values into the four bases of DNA.  We can do this with either of the following methods:
1. Parse two bits of the binary string into A, T, C, or G assigning each of the four permutations of 0 and 1 to A, T, C, or G (e.g. 00=>A, 01=>T, 10=>C, 11=>G)
2. Change our code that takes decimal ASCII values from returning a binary string to returning a base-4 string, and assign each of 0, 1, 2, and 3 to A, T, C, and G (e.g. 0=>A, 1=>T, 2=>C, 3=>G)

**Comment by EdmundKorley** [comment]
I think the latter is the better and simpler way to go right now. I've commented on what would need to change on the last pull-request here: #5

**Comment by hlpostman** [comment]
Once we chose route (2) from the initial comment, this issue really had two parts - change binary to base 4, and change base 4 to DNA.  Closing because we changed binary to base 4.  Opening new issue to change base 4 to DNA.
